language: node_js
node_js:
  - "node"
  - "6"

dist: trusty
sudo: false

addons:
  code_climate:
    repo_token: 28205bd0e861a1fb754df89e0085b84a7fde079e90dbf235fb9451e885a2cc4b
  apt:
    packages:
      - google-chrome-stable  

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info      